routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'adminController@index')->name('admin.index');
Route::resource('seasons', 'SeasonController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = ['name', 'title','text','author', 'league_id'];
}

app/Club.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model
{

    protected $fillable = ['name', 'short_name','nick_name','color','embed', 'photo', 'captain', 'vice_captain', 'gallery_id'];

    public function player()
    {
        return $this->hasmany(Player::class);

    }

    public function fixture()
    {
        return $this->belongsToMany(Fixture::class);

    }

}

app/Detail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detail extends Model
{
    protected $fillable = ['typ', 'match_id','player_id'];
}

app/Fixture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fixture extends Model
{
    protected $fillable = ['data', 'number_fixtures','league_id','season_id'];

    public function club()
    {
        return $this->belongsToMany(Club::class);
    }
}

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = ['name'];
}

app/LeagDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LeagDetail extends Model
{
    //
}

app/League.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class League extends Model
{
    protected $fillable = ['name', 'type_league_id'];
}

app/Localisation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Localisation extends Model
{
    protected $fillable = ['name', 'address'];
}

app/Match.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Match extends Model

{
    protected $fillable = ['title', 'body','data','league_id','localisation_id', 'referee_id', 'gallery_id', 'article_id'];


    public function squad()
    {
        return $this->hasmany(Squad::class);

    }
}

app/Player.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    protected $fillable = ['name', 'surname','nick_name','year_born','gender', 'height', 'weight', 'position', 'photo', 'gallery_id'];
}

app/Referee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Referee extends Model
{
    protected $fillable = ['name', 'surname'];
}

app/Season.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Season extends Model
{
    protected $table = 'seasons2fggdsfg';

    protected $primaryKey = 'sdfsf';

    protected $fillable = ['date', 'archive'];
}

app/Squad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Squad extends Model
{

    protected $fillable = ['club_id'];


    public function player()
    {
        return $this->hasmany(Player::class);

    }
}

app/Trophie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trophie extends Model
{
    protected $fillable = ['name', 'club_id','player_id','league_id'];
}

app/Type_league.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type_league extends Model
{
    protected $fillable = ['name', 'season_id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SeasonController.php
<?php

namespace App\Http\Controllers;

use App\Season;
use Illuminate\Http\Request;

class SeasonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $seasons = Season::paginate(10);

        return view('season.index', [
            'season' => $seasons
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('season.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Season::create($request->all());
        return redirect(route('seasons.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
//
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Season $seasons
     * @return \Illuminate\Http\Response
     */
    public function edit(Season $seasons)
    {

        dump($seasons->date);
        return view('season.edit', [
            'seasons' => $seasons
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Season $seasons
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Season $seasons)
    {
        $seasons->update($request->all());
        return redirect(route('seasons.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/adminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class adminController extends Controller
{


    public function index()
    {
        return view('admin.index');
    }
}

resources/views/admin/index.blade.php
@extends('layouts.app')


@section('content')
    czesc
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            @yield('content')
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/index.blade.php
<html !DOCTYPE>
<head>
    <title>Admin</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset("css/styles.css") }}" />
</head>
<body>




@yield('content')


<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script src="{{ asset("js/sidebar.js") }}"></script>



</body>
</html>

resources/views/layouts/plane.blade.php
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
	<meta charset="utf-8"/>
	<title>@yield('title') -Soccer CMS</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport"/>
	<meta content="" name="description"/>
	<meta content="" name="author"/>

	<link rel="stylesheet" href="{{ asset("assets/stylesheets/styles.css") }}" />
</head>
<body>
	@yield('body')
	<script src="{{ asset("assets/scripts/frontend.js") }}" type="text/javascript"></script>
</body>
</html>

resources/views/season/create.blade.php
@extends('layouts.dashboard')
@section('title', 'Lista sezonów')
@section('page_heading')
    Dodaj sezon
@endsection

@section('section')

{!! Form::open(['route' => 'seasons.store', 'class' => 'form-group']) !!}

{!! Form::label('date', 'data sezonu:') !!}
{!! Form::date('date', null, ['placeholders' => 'data...']) !!}
{!! Form::label('archive', 'Archiwum:') !!}
{!! Form::text('archive', null, ['placeholders' => 'Czy archiwum...']) !!}
<button class="btn btn-info btn-circle"><i class="fa fa-check"></i></button>
    {!! Form::close() !!}



@endsection

resources/views/season/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Edytuj sezon')
@section('page_heading')
    Edycja sezonów
@endsection

@section('section')

{!! Form::open(['route' => ['seasons.update', $seasons], 'method' => 'put']) !!}

{!! Form::label('date', 'data sezonu:') !!}
{!! Form::date('date', $seasons->date) !!}
{!! Form::label('archive', 'Archiwum:') !!}
{!! Form::text('archive', $seasons->archive) !!}
<button class="btn btn-info btn-circle"><i class="fa fa-check"></i></button>
    {!! Form::close() !!}



@endsection

resources/views/season/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Lista sezonów')
@section('page_heading')
    Zarzadzanie sezonami
@endsection

@section('section')

    <a href="{{route('seasons.create')}}" class="btn btn-primary">Dodaj</a>

            <table class="table table-hover">
                <tr>
                    <td>Id</td>
                    <td>Date</td>
                    <td>Edit</td>
                    <td>Delete</td>
                </tr>
            @foreach($season as $item)
                <tr>
                    <td>{{$item->id}}</td>
                    <td>{{$item->date}}</td>
                    <td><a href="{{route('seasons.edit', $item)}}" class="btn btn-primary">Edytuj</a></td>
                    <td><a href="{{route('seasons.create')}}" class="btn btn-primary">Usuń</a></td>
                </tr>

            @endforeach

            </table>



@endsection

resources/views/widgets/alert.blade.php
<div class="alert alert-{{$class}} @if (isset($dismissable)) alert-dismissable @endif" role="alert">
@if (isset($dismissable)) <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> @endif <i class="fa fa-{{ (isset($icon)) ? $icon : $class }}"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @if (isset($link))  <a href="#" class="alert-link">{{ $link }} </a> @endif {{ $message }}.
</div>

resources/views/widgets/badge.blade.php
<span class="badge">{{ $value }}</span>

resources/views/widgets/bglyphicons.blade.php
<button type="button" class="btn btn-default">
<span class="glyphicon glyphicon-{{$class}}" aria-hidden="true"></span> {{$class}}
</button>

resources/views/widgets/button.blade.php
<button type="button" class="btn btn-{{{ isset($class) ? $class : 'default' }}} {{{ isset($rounded) ? 'btn-rounded' : ''}}} {{{ isset($bordered) ? 'btn-bordered' : ''}}} @if (isset($size)) btn-{{$size}} @endif  {{{ isset($disabled) ? 'disabled' : '' }}}">{{ $value }}</button> 

	 

resources/views/widgets/buttongroup.blade.php
<div class="btn-group {{{ isset($large) ? 'btn-group-lg' : ''}}} {{{ isset($small) ? 'btn-group-sm' : ''}}} {{{ isset($extrasmall) ? 'btn-group-xs' : ''}}}" role="group" aria-label="...">
  <button type="button" class="btn btn-default">{{$value1}}</button>
  <button type="button" class="btn btn-default">{{$value2}}</button>
  <button type="button" class="btn btn-default">{{$value3}}</button>
  <button type="button" class="btn btn-default">{{$value4}}</button>
</div>
	 

resources/views/widgets/charts/areachart.blade.php
	

<div id="areachart"></div>

resources/views/widgets/charts/cbarchart.blade.php
<canvas id="cbar" width="350" height="220"></canvas>

resources/views/widgets/charts/cdonutchart.blade.php
<canvas class ="round" id="cdonut" width="250" height="195"></canvas>

resources/views/widgets/charts/clinechart.blade.php
<canvas id="cline" width="350" height="220"></canvas>

resources/views/widgets/charts/cpiechart.blade.php
<canvas class ="round" id="cpie" width="250" height="200"></canvas>

resources/views/widgets/charts/donutchart.blade.php
<div id="donutchart"></div>

resources/views/widgets/charts/linechart.blade.php
	

<div id="linechart"></div>

resources/views/widgets/charts/piechart.blade.php
<div id="piechart"></div>

resources/views/widgets/forms.blade.php
<div class="row">
  <div class="col-sm-4">
    <form>
      <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter name">
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox"> Check me out
        </label>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
<div class="col-sm-3"></div>
  <div class="col-sm-5">

    <div class="onoffswitch">
      <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
      <label class="onoffswitch-label" for="myonoffswitch">
        <span class="onoffswitch-inner"></span>
        <span class="onoffswitch-switch"></span>
      </label>
    </div>
<div class="onoffswitch2">
    <input type="checkbox" name="onoffswitch2" class="onoffswitch-checkbox2" id="myonoffswitch2" checked>
    <label class="onoffswitch-label2" for="myonoffswitch2">
        <span class="onoffswitch-inner2"></span>
        <span class="onoffswitch-switch2"></span>
    </label>
</div>
  </div>
</div>
<div class="row">
  <div class="col-sm-8">
    <p>Add <code>.form-search</code> to the form and <code>.search-query</code> to the <code>input</code> for an extra-rounded text input.</p>
    <form class="form-search">
      <input type="text" class="border-radius-none input-medium search-query">
      <button type="submit" class="btn btn-primary">Search</button>
    </form>
  </div>
</div>

resources/views/widgets/icon.blade.php
<i class="fa fa-{{$class}}"></i>

resources/views/widgets/navbar.blade.php
<nav class="navbar navbar-{{$class}}">
  <div class="container-fluid">
        <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

resources/views/widgets/panel.blade.php
<div class="panel panel-{{{ isset($class) ? $class : 'default' }}}">
	@if( isset($header))  
		<div class="panel-heading">
		<h3 class="panel-title">@yield ($as . '_panel_title')
		@if( isset($controls))  
	<div class="panel-control pull-right">
		<a class="panelButton"><i class="fa fa-refresh"></i></a>
		<a class="panelButton"><i class="fa fa-minus"></i></a>
		<a class="panelButton"><i class="fa fa-remove"></i></a>
	</div>
	@endif
	</h3>
	
	</div>
	@endif
	
	<div class="panel-body">
		@yield ($as . '_panel_body')
	</div>
	@if( isset($footer))
		<div class="panel-footer">@yield ($as . '_panel_footer')</div>
	@endif
</div>

resources/views/widgets/popup.blade.php
data-toggle="popover" data-placement="{{$direction}}" title="" data-original-title= "{{ $title}}" data-content="{{ $content }}"       
             

resources/views/widgets/stacked-progress.blade.php
<div class="progress">
  <div class="progress-bar {{ $class1 }}" style="width: {{ $value1 }}%">
    <span class="sr-only">35% Complete (success)</span>
  </div>
  <div class="progress-bar {{ $class2 }}" style="width: {{ $value2 }}%">
    <span class="sr-only">20% Complete (warning)</span>
  </div>
  <div class="progress-bar {{ $class3 }}" style="width: {{ $value3 }}%">
    <span class="sr-only">10% Complete (danger)</span>
  </div>
</div>

resources/views/widgets/stat.blade.php
<div class="stats">
<div class="bg-{{$color}}">
		<div class=""><i class="fa fa-{{ $icon }} fa-5x"></i></div>
		<h3 align="center">{{ $value }}</h3>
		<p>{{ $header }}</p>	
		<a href="{{ $href }}">View details <i class="fa fa-arrow-circle-right"></i></a>
	</div>
</div>

resources/views/widgets/table.blade.php
<table class="table {{ $class }}">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Address</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>John</td>
			<td>john@gmail.com</td>
			<td>London, UK</td>
		</tr>
		<tr>
			<td>Andy</td>
			<td>andygmail.com</td>
			<td>Merseyside, UK</td>
		</tr>
		<tr>
			<td>Frank</td>
			<td>frank@gmail.com</td>
			<td>Southampton, UK</td>
		</tr>
	</tbody>
</table>

resources/views/widgets/tooltip.blade.php
data-toggle="tooltip" data-placement="{{$direction}}" title="" data-original-title="{{$message}}"             
            
          
             